### ISSUE TITLE
[Bug]: Pi Agent crashes in finishPromptRun for the official DeepSeek provider

### ISSUE THREAD

**Issue by SiinXu** [CherryHQ/cherry-studio#19629]
## Summary

On Windows, a Pi-runtime Agent using Cherry Studio's default official DeepSeek provider fails at the end of a prompt run with `config.startsWith is not a function`. Regular chat still works, and the Agent works when switched to a third-party DeepSeek provider.

## Environment

- Platform: Windows packaged build
- Cherry Studio: current V2 build; exact version was not captured
- Runtime: Pi Agent
- Provider: default official DeepSeek configuration
- Control: regular chat works; a third-party DeepSeek provider works in Agent mode

## Steps to reproduce

1. Configure the default official DeepSeek provider.
2. Open an Agent that uses the Pi runtime.
3. Send a task and wait for the prompt run to finish.
4. Observe the Agent fail with the error below.
5. Run regular chat with the same official provider; it succeeds.
6. Switch the Agent to a third-party DeepSeek provider; it succeeds.

## Actual result

```text
Error: config.startsWith is not a function
    at PiRuntimeConnection.finishPromptRun (.../out/main/main.js:130105:57)
    at .../out/main/main.js:129984:54
```

The Agent path is blocked while regular chat remains usable.

## Expected result

Provider configuration is normalized before `finishPromptRun` inspects it, and the official DeepSeek provider completes Agent runs without a runtime type error.

## Impact

Users of the default official DeepSeek provider cannot use Agent mode. Switching to a third-party provider is the only reported workaround.

## Additional evidence

A maintainer in the private support group confirmed that the root cause had been identified, but no solution or release was available at the time of the report. No private conversation identifiers or attachments are included here.

## Acceptance criteria

- The official DeepSeek provider completes a Pi Agent prompt run on Windows.
- `finishPromptRun` safely handles every supported provider-config shape without calling string methods on non-strings.
- Regular chat and Agent mode use a consistent normalized provider configuration.
- Regression coverage includes the official DeepSeek provider and a custom/third-party provider.
- If configuration is invalid, the user receives an actionable provider error instead of a JavaScript type error.

**Comment by SiinXu** [comment]
Thanks for reporting this. The `config.startsWith is not a function` failure is already fixed on `main` by #19592 (`5ed7d6fff2`). That change normalizes non-string provider `extraHeaders` before Pi resolves them and adds a regression test using Pi’s real `ModelRegistry`/`AuthStorage` path. Closing this as a duplicate of #19592.
