### ISSUE TITLE
[Feature]: Restore the "subscription source" feature for web search blacklist (supported in v1, missing in v2)

### ISSUE THREAD

**Issue by lukepushsolo** [CherryHQ/cherry-studio#18220]
> This issue was translated automatically.

### Pre-submission Checklist

- [x] I understand that Issues are for feedback and problem-solving, not for venting, and I will provide as much information as possible to help resolve the issue.
- [x] I have checked the **pinned Issues** and searched existing [open Issues](https://github.com/CherryHQ/cherry-studio/issues) and [closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed) as well as [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), and did not find similar suggestions.
- [x] I have provided a short, clear, and descriptive title so that developers can quickly identify the general issue when browsing the Issue list.
- [x] The latest version of Cherry Studio does not implement the feature I am proposing.

### Platform

Windows

### Version

v2.0.2

### Is your feature request related to a problem/issue?

In version v1.x, the web search blacklist supported two configuration methods: "manual rules + subscription sources". The subscription source feature was implemented via #2556 and fixed via #6083. After upgrading to v2.0.2, the `Settings → Web Search → Blacklist` area only has the manual input box left; the subscription source (adding subscription URLs, updating rules) feature has disappeared, and the official documentation still describes support for subscription sources, which is inconsistent with the actual implementation.

### Describe the solution you'd like

Restore the v1 blacklist subscription source feature, supporting:

1. Adding subscription source URLs in uBlacklist format (e.g., community-maintained lists like eallion/uBlacklist-subscription-compilation, laylavish/uBlockOrigin-HUGE-AI-Blocklist)
2. Manually triggering updates / periodically auto-updating subscription rules
3. Merging subscription rules with manual rules to take effect together

### Describe alternatives you've considered

If the subscription mechanism cannot be fully restored in the short term, consider:

- Supporting bulk import of blacklist rules from a local file
- While retaining excludeDomains in the v2 data path, adding a subscription source storage field to prepare for future restoration

### Additional context

- Related historical issues: #2556 (completed), #6083 (fixed), #3554 (duplicate of #2556)
- Official documentation still claims support for subscription sources: cherry-studio-docs/blacklist.md
- v2 web-search-settings migration PR: #14993

---
<details>
<summary>Original Content</summary>

### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我已经查看了**置顶 Issue** 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed)以及 [Discussions](https://github.com/CherryHQ/cherry-studio/discussions)，没有找到类似的建议。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。
- [x] 最新的 Cherry Studio 版本没有实现我所提出的功能。

### 平台

Windows

### 版本

v2.0.2

### 您的功能建议是否与某个问题/issue相关?

v1.x 版本中，网络搜索黑名单支持「手动规则 + 订阅源」两种配置方式，订阅源功能通过 #2556 实现、经 #6083 修复。升级到 v2.0.2 后，`设置 → 网络搜索 → 黑名单` 区域仅剩下手动输入框，订阅源（添加订阅 URL、更新规则）功能消失，且官方文档仍描述支持订阅源，与实际不符。

### 请描述您希望实现的解决方案

恢复 v1 的黑名单订阅源功能，支持：

1. 添加 uBlacklist 格式的订阅源 URL（如 eallion/uBlacklist-subscription-compilation、laylavish/uBlockOrigin-HUGE-AI-Blocklist 等社区维护名单）
2. 手动触发更新 / 定期自动更新订阅规则
3. 订阅规则与手动规则合并生效

### 请描述您考虑过的其他方案

若短期无法完整恢复订阅机制，可考虑：

- 支持从本地文件批量导入黑名单规则
- 在 v2 数据路径保留 excludeDomains 的同时，新增订阅源存储字段，为后续恢复做准备

### 其他补充信息

- 相关历史 issue：#2556（已 completed）、#6083（已 fixed）、#3554（#2556 重复）
- 官方文档仍声明支持订阅源：cherry-studio-docs/blacklist.md
- v2 web-search-settings 迁移 PR：#14993
</details>
