### ISSUE TITLE
[Bug]: Adding folder for agent becomes adding files on Ubuntu 20.04

### ISSUE THREAD

**Issue by ZhaoGY-N** [CherryHQ/cherry-studio#11912]
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] My issue is not listed in the [FAQ](https://github.com/CherryHQ/cherry-studio/issues/3881).
- [x] I've looked at **pinned issues** and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.
- [x] I've confirmed that I am using the latest version of Cherry Studio.

### Platform

Linux

### Version

v1.7.3

### Bug Description

When I tried to add an agent, the directory pick did not choose a directory.
Thought the titile named "pick up a directory", I can only pick up a file, as showen in the picture under.
And after that, the agent can not work, reporting "spawn ENOTDIR". The detailed error log output is appended. 
By the way, I can only choose some of the model when select model.

cherry studio is appimage version.

<img width="1252" height="663" alt="Image" src="https://github.com/user-attachments/assets/9d679906-09f9-461c-aef8-6354ca493115" />

<img width="628" height="721" alt="Image" src="https://github.com/user-attachments/assets/b8a8b2d8-1bc2-427d-b9ab-94da71b726e1" />

<img width="1783" height="1206" alt="Image" src="https://github.com/user-attachments/assets/06fd8ece-f72a-4db4-bb19-02a68df21618" />

### Steps To Reproduce

1. click "add assistant"
2. choose "Add agent"
3. add directory in "accessible directories"

### Expected Behavior

Getting a working agent

### Relevant Log Output

```shell
错误名称: AI_ProviderSpecificError
错误信息: spawn ENOTDIR
堆栈信息: AI_ProviderSpecificError: spawn ENOTDIR
    at AiSdkToChunkAdapter.convertAndEmitChunk (file:///tmp/.mount_Cherryi4jHVI/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46487:64)
    at AiSdkToChunkAdapter.readFullStream (file:///tmp/.mount_Cherryi4jHVI/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46305:10)
    at async AiSdkToChunkAdapter.processStream (file:///tmp/.mount_Cherryi4jHVI/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46274:31)
    at async fetchAndProcessAgentResponseImpl (file:///tmp/.mount_Cherryi4jHVI/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:51595:3)
    at async file:///tmp/.mount_Cherryi4jHVI/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:51772:5
    at async file:///tmp/.mount_Cherryi4jHVI/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:49024:21
错误原因: {
  "message": "spawn ENOTDIR",
  "type": "stream_error",
  "code": "stream_processing_failed"
}
```

**Comment by iamsxm** [comment]
> [!NOTE]
> This issue comment was translated by Claude.

When I use newapi it also reports a bug:

``` javascript
Error Name: AI_ProviderSpecificError
Error Message: Failed to fetch
Stack Information: AI_ProviderSpecificError: Failed to fetch at AiSdkToChunkAdapter.convertAndEmitChunk (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46487:64) at AiSdkToChunkAdapter.readFullStream (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46305:10) at async AiSdkToChunkAdapter.processStream (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46274:31) at async ModernAiProvider.modernCompletions (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:260826:22) at async ModernAiProvider._completionsOrImageGeneration (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:260747:10) at async ModernAiProvider.completions (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:260730:17) at async fetchChatCompletion (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:263220:2) at async transformMessagesAndFetch (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:50087:3) at async fetchAndProcessAssistantResponseImpl (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:51706:3) at async file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:52006:4)
Error Cause: {}
```

---
<details>
<summary>Original Content</summary>

when i usr newapi it also report bug:

``` javascript
错误名称: AI_ProviderSpecificError 错误信息: Failed to fetch 堆栈信息: AI_ProviderSpecificError: Failed to fetch at AiSdkToChunkAdapter.convertAndEmitChunk (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46487:64) at AiSdkToChunkAdapter.readFullStream (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46305:10) at async AiSdkToChunkAdapter.processStream (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46274:31) at async ModernAiProvider.modernCompletions (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:260826:22) at async ModernAiProvider._completionsOrImageGeneration (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:260747:10) at async ModernAiProvider.completions (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:260730:17) at async fetchChatCompletion (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:263220:2) at async transformMessagesAndFetch (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:50087:3) at async fetchAndProcessAssistantResponseImpl (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:51706:3) at async file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:52006:4 错误原因: {}
```
</details>

**Comment by iamsxm** [comment]
> [!NOTE]
> This issue/comment/review was translated by Claude.

> when i usr newapi it also report bug:
> 
> Error Name: AI_ProviderSpecificError Error Message: Failed to fetch Stack Trace: AI_ProviderSpecificError: Failed to fetch at AiSdkToChunkAdapter.convertAndEmitChunk (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46487:64) at AiSdkToChunkAdapter.readFullStream (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46305:10) at async AiSdkToChunkAdapter.processStream (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46274:31) at async ModernAiProvider.modernCompletions (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:260826:22) at async ModernAiProvider._completionsOrImageGeneration (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:260747:10) at async ModernAiProvider.completions (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:260730:17) at async fetchChatCompletion (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:263220:2) at async transformMessagesAndFetch (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:50087:3) at async fetchAndProcessAssistantResponseImpl (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:51706:3) at async file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:52006:4 Error Cause: {}

And it works in v1.7.2

---
<details>
<summary>Original Content</summary>

> when i usr newapi it also report bug:
> 
> 错误名称: AI_ProviderSpecificError 错误信息: Failed to fetch 堆栈信息: AI_ProviderSpecificError: Failed to fetch at AiSdkToChunkAdapter.convertAndEmitChunk (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46487:64) at AiSdkToChunkAdapter.readFullStream (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46305:10) at async AiSdkToChunkAdapter.processStream (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:46274:31) at async ModernAiProvider.modernCompletions (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:260826:22) at async ModernAiProvider._completionsOrImageGeneration (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:260747:10) at async ModernAiProvider.completions (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:260730:17) at async fetchChatCompletion (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:263220:2) at async transformMessagesAndFetch (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:50087:3) at async fetchAndProcessAssistantResponseImpl (file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:51706:3) at async file:///C:/Users/1/AppData/Local/Programs/Cherry%20Studio/resources/app.asar/out/renderer/assets/store-Oi5sAZNS.js:52006:4 错误原因: {}

And it works in v1.7.2
</details>

**Comment by Jeong-zju** [comment]
same issue
